### ISSUE TITLE
feature checklist

### ISSUE THREAD

**Issue by hasheemi** [hasheemi/jagatirta#1]
### Halaman Utama
- [x] Kerangka halaman
- [ ] Responsive style
- [ ] Integrasi ke database

### Halaman Login
- [x] Kerangka halaman
- [ ] Responsive style
- [ ] Fungsi login with google
- [ ] Halaman dashboard pengguna
- [ ] CRUD ke database

### Halaman Maps
- [x] Kerangka halaman
- [ ] Responsive style
- [ ] Fungsionalitas maps

### Halaman Blog
- [ ] Kerangka halaman
- [ ] Responsive style
- [ ] CRUD konten
- [ ] Labelling and filtering

### Halaman Cuaca
- [ ] Kerangka halaman
- [ ] Responsive style
- [ ] Ambil data pengguna, cuaca, bencana, dan sumber air

### Halaman Community
- [ ] Kerangka halaman
- [ ] Responsive style
